import type { Metadata } from "next";
import { GlishoruFooter, GlishoruHeader } from "../GlishoruShell";

export const metadata: Metadata = { title: "Datenschutz — Restaurant Glishoru", description: "Datenschutzerklärung des Restaurant Glishoru gemäss Schweizer Datenschutzgesetz." };

export default function DatenschutzPage() {
  return <main className="glishoru gSubpage"><GlishoruHeader />
    <section className="gLegalHero"><p className="gEyebrow">Information nach Schweizer DSG</p><h1>Datenschutz</h1></section>
    <section className="gPrivacy">
      <div className="gPrivacyIntro"><p>Diese Datenschutzerklärung informiert darüber, welche Personendaten beim Besuch dieser Website bearbeitet werden. Die Website verwendet kein eigenes Analyse- oder Werbetracking und setzt keine eigenen Marketing-Cookies.</p><p className="gPrivacyDate">Stand: August 2026</p></div>
      <article><span>01</span><div><h2>Verantwortliche Stelle</h2><p>Restaurant Glishoru<br />Schmidhalter Joel<br />Dorfplatz 25, CH-3902 Glis</p><p><a href="mailto:restaurant@glishoru.ch">restaurant@glishoru.ch</a><br /><a href="tel:+41774947777">+41 77 494 77 77</a></p></div></article>
      <article><span>02</span><div><h2>Technische Zugriffsdaten</h2><p>Beim Aufruf der Website werden technisch notwendige Daten verarbeitet. Dazu können IP-Adresse, Datum und Uhrzeit, aufgerufene Seite, übertragene Datenmenge, Browser- und Betriebssystemangaben sowie die zuvor besuchte Seite gehören. Die Bearbeitung dient der sicheren und zuverlässigen Bereitstellung, der Fehleranalyse und dem Schutz vor Missbrauch.</p><p>Die Website wird über OpenAI Sites auf technischer Infrastruktur von Cloudflare bereitgestellt. Dabei können Auftragsbearbeiter Zugriffsdaten in Rechenzentren ausserhalb der Schweiz bearbeiten. Die Daten werden nur so lange aufbewahrt, wie dies für Betrieb, Sicherheit und Missbrauchsabwehr erforderlich ist, und anschliessend gelöscht oder anonymisiert.</p></div></article>
      <article><span>03</span><div><h2>Kontaktaufnahme</h2><p>Wenn Sie uns per Telefon oder E-Mail kontaktieren, bearbeiten wir die von Ihnen übermittelten Angaben, um Ihre Anfrage oder Reservierung zu beantworten. Dazu können Name, Kontaktdaten, Reservierungswünsche und der Inhalt Ihrer Nachricht gehören. Die Angaben werden nicht für fremde Werbezwecke verkauft und nur so lange gespeichert, wie dies für die Bearbeitung oder gesetzliche Aufbewahrungspflichten erforderlich ist.</p></div></article>
      <article><span>04</span><div><h2>Externe Links</h2><p>Instagram, Facebook, Google Maps und die PDF-Speisekarte sind lediglich verlinkt und nicht als Social Plugins oder Karten direkt eingebettet. Erst wenn Sie einen solchen Link anklicken, wird eine Verbindung zum jeweiligen Anbieter hergestellt. Dabei gelten die Datenschutzbestimmungen dieses Anbieters; Daten können auch in Staaten ausserhalb der Schweiz bearbeitet werden.</p></div></article>
      <article><span>05</span><div><h2>Cookies und Analyse</h2><p>Diese Website verwendet nach aktuellem Stand keine eigenen Analyse-, Marketing- oder Profilingdienste und keine dafür bestimmten Cookies. Technisch notwendige Funktionen des Hostingdienstes können sicherheitsrelevante Informationen verarbeiten. Sollte später Tracking, ein Kontaktformular, ein Reservierungssystem oder ein eingebetteter Drittinhalt ergänzt werden, wird diese Erklärung vor dessen Aktivierung angepasst.</p></div></article>
      <article><span>06</span><div><h2>Ihre Rechte</h2><p>Im Rahmen des anwendbaren Schweizer Datenschutzrechts können Sie insbesondere Auskunft über Ihre bearbeiteten Personendaten sowie deren Berichtigung oder Löschung verlangen. Sie können einer Bearbeitung widersprechen oder die Herausgabe bestimmter Daten verlangen, soweit die gesetzlichen Voraussetzungen erfüllt sind. Bitte richten Sie entsprechende Anfragen an die oben genannte Kontaktadresse.</p></div></article>
      <article><span>07</span><div><h2>Datensicherheit und Änderungen</h2><p>Wir treffen angemessene technische und organisatorische Massnahmen zum Schutz von Personendaten. Die Übertragung dieser Website erfolgt verschlüsselt. Diese Erklärung kann angepasst werden, wenn sich Funktionen, Dienstleister oder rechtliche Anforderungen ändern. Es gilt die jeweils auf dieser Seite veröffentlichte Fassung.</p></div></article>
    </section>
    <GlishoruFooter />
  </main>;
}
